### ISSUE TITLE
Problems generating FLIRT BBR reportlets

### ISSUE THREAD

**Issue by oesteban** [nipreps/niworkflows#559]
```
Node Name: fmriprep_wf.single_subject_100104_wf.func_preproc_task_machinegame_run_001_wf.bold_reg_wf.fsl_bbr_wf.flt_bbr

File: /oak/stanford/groups/russpold/data/ds000054/0.0.5/derivatives/fmriprep-20.2.0rc0/fmriprep/sub-100104/log/20200827-094552_164fe55c-bbf2-4682-aaeb-10edf72f3ccb/crash-20200827-110133-oesteban-flt_bbr-7ebe8bf9-77cd-4a80-bd91-cdc1bcbedc63.txt
Working Directory: /lscratch/100104/fmriprep_wf/single_subject_100104_wf/func_preproc_task_machinegame_run_001_wf/bold_reg_wf/fsl_bbr_wf/flt_bbr
Inputs:
angle_rep:
apply_isoxfm:
apply_xfm:
args:
bbrslope:
bbrtype:
bgvalue:
bins:
coarse_search:
compress_report: auto
cost:
cost_func: bbr
datatype:
display_init:
dof: 6
echospacing:
environ: {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
fieldmap:
fieldmapmask:
fine_search:
force_scaling:
in_file:
in_matrix_file:
in_weight:
interp:
min_sampling:
no_clamp:
no_resample:
no_resample_blur:
no_search:
out_file:
out_log:
out_matrix_file:
out_report: report.svg
output_type: NIFTI_GZ
padding_size:
pedir:
ref_weight:
reference:
rigid2D:
save_log:
schedule: /usr/share/fsl/5.0/etc/flirtsch/bbr.sch
searchr_x:
searchr_y:
searchr_z:
sinc_width:
sinc_window:
uses_qform:
verbose:
wm_seg:
wmcoords:
wmnorms:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/registration.py", line 214, in _post_run_hook
    return super(FLIRTRPT, self)._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/report_base.py", line 79, in _generate_report
    compress=self.inputs.compress_report,
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py", line 337, in plot_registration
    svg = extract_svg(display, compress=compress)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py", line 124, in extract_svg
    image_svg = svg2str(display_object, dpi)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py", line 117, in svg2str
    image_buf, dpi=dpi, format="svg", facecolor="k", edgecolor="k"
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/figure.py", line 2035, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/backends/backend_svg.py", line 1210, in print_svg
    result = self._print_svg(filename, fh, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/backends/backend_svg.py", line 1240, in _print_svg
    self.figure.draw(renderer)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2543, in draw
    pos = locator(self, renderer)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/plotting/displays.py", line 1649, in _locator
    return transforms.Bbox([[left_dict[axes], y0],
KeyError: 
```

**Comment by oesteban** [comment]
This is similar, this time plotting some mask. This error only occurred for 2 out of 5 runs (ds210/sub-07). The only two where the FLIRT BBR was rejected (I assume that the cause of the problem must be similar).

```
Node Name: fmriprep_wf.single_subject_07_wf.func_preproc_task_cuedSGT_run_02_echo_1_wf.skullstrip_bold_wf.mask_reportlet

File: /oak/stanford/groups/russpold/data/openneuro.org/derivatives/ds000210/fmriprep-20.2.0rc1/fmriprep/sub-07/log/20200828-034631_ecf983ae-2ef8-4fb1-af16-85b499054b65/crash-20200828-035405-oesteban-mask_reportlet.a1-c1e5d2a9-37b5-4c11-be68-2a4c14115be7.txt
Working Directory: /lscratch/07/fmriprep_wf/single_subject_07_wf/func_preproc_task_cuedSGT_run_02_echo_1_wf/skullstrip_bold_wf/_bold_file_..oak..stanford..groups..russpold..data..openneuro.org..ds000210..sub-07..func..sub-07_task-cuedSGT_run-02_echo-2_bold.nii.gz/mask_reportlet
Inputs:
background_file:
compress_report: auto
mask_file:
out_report: report.svg
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 420, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/masks.py", line 273, in _post_run_hook
    return super(SimpleShowMaskRPT, self)._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/report_base.py", line 107, in _generate_report
    compress=self.inputs.compress_report,
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py", line 253, in plot_segs
    image_nii, segs=seg_niis, compress=compress, **plot_params
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py", line 290, in _plot_anat_with_contours
    svg = extract_svg(display, compress=compress)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py", line 125, in extract_svg
    image_svg = svg2str(display_object, dpi)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py", line 118, in svg2str
    image_buf, dpi=dpi, format="svg", facecolor="k", edgecolor="k"
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/figure.py", line 2035, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/backends/backend_svg.py", line 1210, in print_svg
    result = self._print_svg(filename, fh, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/backends/backend_svg.py", line 1240, in _print_svg
    self.figure.draw(renderer)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2543, in draw
    pos = locator(self, renderer)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/plotting/displays.py", line 1649, in _locator
    return transforms.Bbox([[left_dict[axes], y0],
KeyError: 
```
