### ISSUE TITLE
mriqc not installed as dependency

### ISSUE THREAD

**Issue by sjshim** [nipreps/niworkflows#875]
### What happened?

After running `$ python -m pip install sdcflows` and running `sdcflows` got the following error

Traceback (most recent call last):
  File "/oak/stanford/groups/russpold/users/sjshim/miniconda3/envs/fmri_analysis/bin/sdcflows", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/oak/stanford/groups/russpold/users/sjshim/miniconda3/envs/fmri_analysis/lib/python3.11/site-packages/sdcflows/cli/main.py", line 178, in main
    "plugin": MultiProcPlugin(
              ^^^^^^^^^^^^^^^^
  File "/oak/stanford/groups/russpold/users/sjshim/miniconda3/envs/fmri_analysis/lib/python3.11/site-packages/niworkflows/engine/plugin.py", line 416, in __init__
    from mriqc import config
ModuleNotFoundError: No module named 'mriqc'

It was resolved once I pip installed mriqc

### What command did you use?

```shell
sdcflows BIDS sdcflow/ participant
```

### What version of the software are you running?

2.9.0

### How are you running this software?

Local installation ("bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
Okay, this is actually a niworkflows bug, but it's affecting sdcflows.

I guess we need to release niworkflows 1.10.3 and sdcflows 2.9.1, depending on this?
