### ISSUE TITLE
Data loader fails with NiWorkflows installed in editable mode

### ISSUE THREAD

**Issue by oesteban** [nipreps/niworkflows#884]
### What happened?

Getting:

```
Node: mriqc_wf.funcMRIQC.SpatialNormalization.EPI2MNI
Working directory: /home/oesteban/tmp/hcph-mriqc/work/mriqc_wf/funcMRIQC/SpatialNormalization/d72b6e07efe0979e9d50d06bbb8c3f4cc4361d0d/EPI2MNI

Node inputs:

compress_report = auto
explicit_masking = False
flavor = precise
float = False
initial_moving_transform = <undefined>
lesion_mask = <undefined>
moving = boldref
moving_image = /home/oesteban/tmp/hcph-mriqc/work/mriqc_wf/funcMRIQC/SpatialNormalization/d72b6e07efe0979e9d50d06bbb8c3f4cc4361d0d/SharpenEPI/sub-001_ses-001_task-bht_dir-LR_echo-1_part-mag_desc-realigned_bold_tstat_corrected.nii.gz
moving_mask = /home/oesteban/tmp/hcph-mriqc/work/mriqc_wf/funcMRIQC/synthstrip_wf/d72b6e07efe0979e9d50d06bbb8c3f4cc4361d0d/synthstrip/clipped_corrected_desc-brain_mask.nii.gz
num_threads = 12
orientation = RAS
out_report = report.svg
reference = boldref
reference_image = /data/datasets/templateflow-s3/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-fMRIPrep_boldref.nii.gz
reference_mask = /data/datasets/templateflow-s3/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-brain_mask.nii.gz
settings = <undefined>
template = MNI152NLin2009cAsym
template_resolution = <undefined>
template_spec = <undefined>

Traceback (most recent call last):
  File "/home/oesteban/workspace/mriqc/mriqc/engine/plugin.py", line 64, in run_node
    result['result'] = node.run(updatehash=updatehash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node EPI2MNI.

Traceback:
        Traceback (most recent call last):
          File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 397, in run
            runtime = self._run_interface(runtime)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/niworkflows/interfaces/norm.py", line 181, in _run_interface
          File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/niworkflows/interfaces/norm.py", line 171, in _get_settings
          File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/niworkflows/interfaces/norm.py", line 171, in <listcomp>
          File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/pathlib.py", line 931, in iterdir
            for name in os.listdir(self):
                        ^^^^^^^^^^^^^^^^
        FileNotFoundError: [Errno 2] No such file or directory: '/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/niworkflows/data'
```

### What command did you use?

```shell
mriqc
```

### What version of the software are you running?

master

### How are you running this software?

Other

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
This doesn't look editable: `python3.11/site-packages/niworkflows/interfaces/norm.py"`

Is it possible you need to reinstall?

**Comment by oesteban** [comment]
Yes, after reinstalling I couldn't replicate within ipython. Checking with mriqc now. I'll close as soon as I confirm it was a stale environment.
